// Code generated by Kitex v0.12.1. DO NOT EDIT.

package zkserver_operation

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	operations "nrMQ/kitex_gen/operations"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTopic(ctx context.Context, req *operations.CreateTopicRequest, callOptions ...callopt.Option) (r *operations.CreateTopicResponse, err error)
	CreatePart(ctx context.Context, req *operations.CreatePartRequest, callOptions ...callopt.Option) (r *operations.CreatePartResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kZkServer_OperationClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kZkServer_OperationClient struct {
	*kClient
}

func (p *kZkServer_OperationClient) CreateTopic(ctx context.Context, req *operations.CreateTopicRequest, callOptions ...callopt.Option) (r *operations.CreateTopicResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTopic(ctx, req)
}

func (p *kZkServer_OperationClient) CreatePart(ctx context.Context, req *operations.CreatePartRequest, callOptions ...callopt.Option) (r *operations.CreatePartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePart(ctx, req)
}
